### ISSUE TITLE
Extracting ODEProblem from FMU

### ISSUE THREAD

**Issue by PGimenez** [ThummeTo/FMI.jl#147]
Is there an easy way to extract the ODEProblem/ODEFunction from the FMU? 

So far I've hijacked the `fmiSimulateME` function and added `  return problem, customFx`right after

https://github.com/ThummeTo/FMI.jl/blob/8a9afa0ebd5ea1bab41807d1816ac0792f69d444/src/FMI2_sim.jl#L894

I've tried with a simple RC circuit exported from OMEdit, and I'm then able to solve the returned ODE.

**Comment by ThummeTo** [comment]
Would a field in the FMU struct be sufficient?
Like `myFMU.problem` (would be available only for ME-FMUs).

**Comment by PGimenez** [comment]
Yes, that would be perfect!

**Comment by ThummeTo** [comment]
This will be part of FMI.jl v0.10.1:

After simulation, you can access the ODEProblem of a FMU2Component via `comp.problem` or ODEProblem of the FMU via `fmu.components[end].problem`. If you don't want to perform a simulation first, you can use the new command `FMIImport.setupODEProblem(c::FMU2Component, x0::AbstractArray{fmi2Real}, t_start::fmi2Real, t_stop::fmi2Real)` to setup the ODEProblem without simulating.

**Comment by ThummeTo** [comment]
This was added in v0.10.1
