### ISSUE TITLE
FMI Load Function Error

### ISSUE THREAD

**Issue by coprem** [ThummeTo/FMI.jl#17]
fmiLoad Function gives an error  "AssertionError: Target platform is Windows, but can't valid find FMU binary.", the same FMU works fine in fmpy. 

I found that **fmiLoad** function is looking for binary with the same name as FMU name in the unzipped folder, which might not be true in all the cases. FMU Birnarys have the same name as modelIdentifier in modelDescription.xml

I can create a pull request and resolve this issue @ThummeTo

**Comment by ThummeTo** [comment]
Dear @coprem,
thanks for coming up with the issue. You're completely right. If you wish, you can create a quick fix (pull request). Or I will fix the issue in the next push today or tomorrow (there are other outstanding tags that should have been read from the model description like available optional functions).
Thank you!

**Comment by ThummeTo** [comment]
@coprem: Can you check if  #8acfe2b fixed your issue? Thank you!

**Comment by coprem** [comment]
@ThummeTo the Problem with respect to Picking the Correct Name of the dll is resolved.  Now having a Different error "filename or extension is too long" I think the File name length is Limited.

I am not sure of the problem I tried finding the root cause.

**Comment by coprem** [comment]
@ThummeTo 
> How long is the complete path in your case? What system are you using?

68 Characters long, I am using a Windows 10 Machine. 
 
> Can you provide the FMU or does it contain sensible data?
I am sorry I will not be able to share the FMU.

**Comment by ThummeTo** [comment]
@coprem: 68 characters including the FMU name itself? Does the path contain any special characters or does the FMU name contain dots like "Mechanics.Rotation.Components.Fixed.dll"?

**Comment by coprem** [comment]
The path doesn't contain any Issues I tried Loading the SpringDamperPendulum1D.fmu from the same path location and it did work fine. 

The only special character in the name is "_" as shown in the example: Mechanics_Rotation_Components_Fixed.dll.

I conducted the following tests
- tested removing the "_ " from the dll file name keeping the remaining filename to be the same (length 62) - DLL loading failed
- tested reducing the length of the file name keeping "_" and reduced the length to 53 characters - DLL Loading Sucess

more than 53 characters DLL fails to load

`function dlopen(s::AbstractString, flags::Integer = RTLD_LAZY | RTLD_DEEPBIND; throw_error::Bool = true)
    ret = ccall(:jl_load_dynamic_library, Ptr{Cvoid}, (Cstring,UInt32,Cint), s, flags, Cint(throw_error))
    if ret == C_NULL
        return nothing
    end
    return ret
end`

UInt32 is limiting the length of the string I guess

**Comment by coprem** [comment]
@ThummeTo the problem of "filename or extension is too long" this is caused by one Drive my Computer. we can close this Issue Now I am run the FMU.

**Comment by ThummeTo** [comment]
No problem!
