### ISSUE TITLE
Backport compat for SciMLBase@v2 for FMI@v0.10

### ISSUE THREAD

**Issue by SebastianM-C** [ThummeTo/FMI.jl#196]
Hi!

FMI@0.10 is still used in some places and recently SciMLBase released v2 (https://github.com/SciML/SciMLBase.jl#v20-breaking-changes). Would it be possible to create a branch based on 0.10.2 on the repo? Then that could be used to backport the SciMLBase version bump by adding a v2 compat and registering 0.10.3 from the commit.

**Comment by ThummeTo** [comment]
Sure.
Just that I get this right: You need a FMI.jl v0.10.3 registered, that allows for SciMLBase v2 in the project.toml?
If yes, I can do right now.

**Comment by ThummeTo** [comment]
Yep, the only related thing that changed were the new ReturnCodes by the ODE `solve`. I fixed this.
The old tests are running locally now. Registration is triggered.
