### ISSUE TITLE
Relax compat requirements

### ISSUE THREAD

**Issue by mestinso** [ThummeTo/FMI.jl#218]
Some of the current package compat requirements are somewhat restrictive and are causing some surprising package results. These are the main pkg requirements that i'm referring to that I think could be relaxed:
- DifferentialEquations (FMI.jl): Relax from "7.7-7.12" to "7.7"?
- ProgressMeter (FMI.jl): Relax from "1.7-1.9" to "1.7"?
- ChainRulesCore (FMICore.jl): Relax from "1.16-1.18" to "1.16"?

In a fresh environment, if I "] add FMI", the following packages get installed (this is on julia 1.10.1):
FMI.jl = 0.16.4 (latest)
FMIImport.jl = 0.16.3 (not the latest)
FMICore.jl = 0.19.1 (not the latest)

The issue appears to be the new compat requirement here (capping ChainRulesCore to 1.18):
https://github.com/ThummeTo/FMICore.jl/commit/4e53a054b0015460dc500f23aa66fd576490188f

Since DifferentialEquations also depends on ChainRulesCore, Pkg decides to downgrade FMIImport and FMICore to earlier where that compat requirement wasn't present and then it ends up installing version 1.22 of ChainRulesCore. So if FMI really depends on 1.16-1.18, this new restriction ended up backfiring and Pkg found a way to install it anyways...

**Comment by ThummeTo** [comment]
Allowing for any new (possible) breaking release led to some bad crashes in the past for FMI.jl, so I wouldn't do that. However in FMICore it seems ok. So I think the proper way would be to allow for ChainRulesCore 1.16+ in FMICore.

**Comment by mestinso** [comment]
@ThummeTo Didn't want to open a full additional issue here, but what about ProgressMeter compatibility requirements? Seems like a relatively low risk one to relax as well. Thoughts?

**Comment by ThummeTo** [comment]
Relaxing compats for ProgressMeter seems ok for me 👍 
Big update is coming in anyway, so I will implement it there
