### ISSUE TITLE
Error : FMU is not in instantiation mode

### ISSUE THREAD

**Issue by coprem** [ThummeTo/FMI.jl#22]
@ThummeTo 

when the FMU is exported (License Free FMU) using Dymola Solver (4th Option) as shown in the Figure below. 

![image](https://user-images.githubusercontent.com/30013537/124352398-a11b1100-dc1d-11eb-91db-927a9e94efde.png)

` fmiSimulate` gives the error  **FMU is not in instantiation mode** 

the same model when a license-free FMU is generated with Cvode (3rd Option in the figure above). the model works file.

I tried to find the cause of the error but I didn't have any luck.

Note: this error exists in both V 0.1.2 and V 0.1.3. checked FMU with Dymola Solver in FMPy- works fine.

Regards
Prem

**Comment by ThummeTo** [comment]
Hey @coprem,

thanks for opening the issue.
Can you please provide the code for the simulation? 
(If possible the FMU itself helps a lot, too)

BTW: by using fmiSimulateCS or fmiSimulateME you can force simulation in CS or ME mode (CS is used by default if available).

**Comment by ThummeTo** [comment]
Hey @coprem ,

I guess you are entering initialisation mode a second time, which is not allowed using the Dymola solver. `fmiSimulate` already does enter and exit initialisiation mode, so the follwing should work as excpected

**Case A)** Do initialization by yourself:
```
myFMU = fmiLoad(pathToFMU)
fmiInstantiate!(myFMU; loggingOn=true)
fmiSetupExperiment(myFMU, t_start)
fmiEnterInitializationMode(myFMU)
fmiExitInitializationMode(myFMU)
data = fmiSimulateCS(myFMU, t_start, t_stop; recordValues=["mass.s", "mass.v"], setup=false)
fmiPlot(data)
fmiUnload(myFMU)
```

**Case B)** Let fmi.jl initialize:
```
myFMU = fmiLoad(pathToFMU)
fmiInstantiate!(myFMU; loggingOn=true)
data = fmiSimulateCS(myFMU, t_start, t_stop; recordValues=["mass.s", "mass.v"])
fmiPlot(data)
fmiUnload(myFMU)
```

Notice the optional keyword `setup=false` in Case A!

Does this resolve your issue?

**Comment by coprem** [comment]
> Hey @coprem,
> 
> thanks for opening the issue.
> Can you please provide the code for the simulation?
> (If possible the FMU itself helps a lot, too)
> 
> BTW: by using `fmiSimulateCS` or `fmiSimulateME` you can force simulation in CS or ME mode (CS is used by default if available).

**Comment by coprem** [comment]
@ThummeTo  Please find the code below
```
FMU = fmiLoad(modelFMUPath)
myFMU = fmiInstantiate!(FMU; loggingOn=false)
fmiSetupExperiment(myFMU, 0.0)

t_start = 0.0
t_stop =1000.0

fmiEnterInitializationMode(myFMU)
fmiSetReal(myFMU, InputVars, InputValsReal)
fmiExitInitializationMode(myFMU)
result = fmiSimulate(myFMU,t_start, t_stop; recordValues= FMU.modelDescription.outputValueReferences)
```

I will be trying both the approaches Case A and Case B and Will let you know

I am sry that I cannot Provide FMU because of Dymola License Agreement.

**Comment by ThummeTo** [comment]
Adding `setup=false` to your last line should do the trick:

`result = fmiSimulate(myFMU,t_start, t_stop; recordValues= FMU.modelDescription.outputValueReferences, setup=false)`

**Comment by coprem** [comment]
@ThummeTo I have tried with Case A and Case B both of them didn't work with Dymola Solver FMU. it gives the same error: FMU is not in instantiation mode.

**Comment by ThummeTo** [comment]
Dear @coprem ,
can you check if #23 solved your issue CaseA?

Another important point: Do all commands before fmiSimulate succeed (= returning 0x00000000)? Maybe there is a problem during initialization (try loggingOn=true).

**Comment by coprem** [comment]
@ThummeTo #23 has resolved the Issue with Case A and it's working fine.  Thanks.

Note: I Did Test Case B with #23 it gives the same error. but any way Case A Solves my problem.

Regards
Prem

**Comment by ThummeTo** [comment]
Dear @coprem ,

please check if the library version 0.1.4 resolves your issue. If not, please provide a minimal working example consisting of the code and the FMU. If you can't share the FMU, please provide a short export instruction naming a MSL-example, your exporting tool and export settings. Based on this information, we can export a FMU under the same conditions and test it (we are using Dymola as well as OpenModelica).

Thank you!

**Comment by coprem** [comment]
Hi @ThummeTo 

with Version 0.1.4 the issue is Resolved and I tested Both Case A and Case B work fine. 

Closing the Issue.

Regards
Prem
