### ISSUE TITLE
Request for DiffEqCallbacks v3 compat with FMI v0.10.x

### ISSUE THREAD

**Issue by sharanry** [ThummeTo/FMI.jl#222]
Hey @ThummeTo!

This is a request for a patch release on FMI v0.10.x for DiffEqCallbacks v3.x.x.

I already have a branch here for it -- https://github.com/ThummeTo/FMI.jl/compare/v0.10.3...sharanry:sy/bump_diffeqcallback_compat?expand=1

**Comment by ThummeTo** [comment]
HI @sharanry,
sure, just open a PR 👍 
(please also increase the version in project.toml, should be v0.10.4, so we can merge directly if the tests pass)

**Comment by sharanry** [comment]
I can't seem to open a PR as there is not branch for v0.10.

**Comment by sharanry** [comment]
I have updated the branch with a patch bump.

**Comment by ThummeTo** [comment]
I created one (v0.10.4) should be based on the commit of the v0.10.3 release. Now you can open a PR to the v0.10.4 branch, so we can check if the tests are running :-)

**Comment by ThummeTo** [comment]
Registration is in progress :)

**Comment by sharanry** [comment]
Thanks!
