### ISSUE TITLE
Suggestion on Logo Appearance in Dark Theme

### ISSUE THREAD

**Issue by coprem** [ThummeTo/FMI.jl#24]
HI Team 

I know this not trivial, but just giving my observation. FMI.jl logo doesn't have good visibility in dark model as shown in the picture below.

![image](https://user-images.githubusercontent.com/30013537/124649772-89aa8500-deb6-11eb-9f3e-11748c297d19.png)

Julia Logo doesn't have this problem because there is a 1 or 2 Pixel border around each letter so the logo appears even in Dark Mode

![image](https://user-images.githubusercontent.com/30013537/124650337-3d137980-deb7-11eb-9371-d57139f8c18f.png)

Regards
Prem

**Comment by ThummeTo** [comment]
Dear @coprem,
the logo will be adapted to be compatible with light and dark themes.
Thanks for your hint!

**Comment by ThummeTo** [comment]
Closed with PR #37
