### ISSUE TITLE
Problematic compat practices leading to unintended Pkg resolver resolution

### ISSUE THREAD

**Issue by mestinso** [ThummeTo/FMI.jl#244]
I"m noticing that compat updates like the following:
https://github.com/ThummeTo/FMIBase.jl/commit/80e91513f5bf60c0859268c99b1288ea21ec2d73
can have the opposite effect of what is intended in some cases.

From a clean FML.jl install, Pkg is deciding to stay with the lower FMIBase.jl version (1.06) in order to maintain the higher DiffEqCallbacks.jl verslon (3.8).

With that said, if there are really problems with DiffEqCallbacks.jl 3.8, your change seems natural. It's not clear to me if there are better Pkg.jl compat practices that should be used for situations like this or if this is Pkg.jl issue.

My thinking is that since FMIBase depends on DiffEqCallbacks (and not the other way around), it's version being up to date should take precedence. I'm tempted to open an issue over at Pkg.jl, but a) I wanted to discuss the issue here first, and b) ideally i'd like to describe the problem as simple as possible with a MWE before taking it to Pkg.jl issue board.

Anyways, here is the situation i ran on julia 1.11 with FMI.jl only installed:
![image](https://github.com/user-attachments/assets/5de20da8-b755-4c50-98c3-5975d83ad92b)

**Comment by ThummeTo** [comment]
That is interesting! Indeed there where issues with DiffEqCallbacks 3.8 thats why the downgrade. 

The fact that DiffEqCallbacks keeps FMIBase on a lower release seems strange... can you try removing the explicit dependency to DiffEqCallbacks and check if this solves the issue? Maybe resolve afterwards too?

**Comment by ThummeTo** [comment]
Ok, I can reproduce this, but it feels (as you are saying) not very intuitive...
I will fix FMIImport v1.0.6 to FMIBase v1.0.8 (and upper), so that the next FMI/FMIFlux releases will force the new FMIBase release

**Comment by ThummeTo** [comment]
should be closed with v0.14.1 - please reopen if not

**Comment by mestinso** [comment]
@ThummeTo Confirmed resolved here. Any lingering thoughts from your point of view with respect reporting the issue to Pkg.jl? I will note that I previously saw this same type of issue with PythonCall.jl when a dependency was rolled back.

**Comment by ThummeTo** [comment]
IMO this behavior is unexpected, but I don't know what the _intended_ behavior of Pkg is. If this is not intended, opening an issue would be definitely the right way to go...
