### ISSUE TITLE
Error: The filename or extension is too long

### ISSUE THREAD

**Issue by coprem** [ThummeTo/FMI.jl#25]
Hi @ThummeTo 

when I placed my FMU in the folder where the path is 136 char, function `fmiLoad` gives an error **The filename or extension is too long.**

Based on my understanding to avoid this problem, it would be nice to create a folder (with some random name) in the Temp folder (in Windows "C:\Users\username\AppData\Local\Temp" ) to extract the FMU and use the FMU files, in this way the length of the path will not be an issue.

Regards
Prem

**Comment by ThummeTo** [comment]
Dear @coprem ,

please check if the library version 0.1.4 resolves your issue. You can now control where the FMU is unpacked via optional keyword argument `unpackPath`:

```
fmiLoad(pathToFMU::String; unpackPath=nothing)
fmi2Load(pathToFMU::String; unpackPath=nothing)
```

If you don't use the keyword ( `unpackPath=nothing`) the ZIP-Archive is unpacked in your system's temporary directory as suggested.

Thank you!

**Comment by coprem** [comment]
Hi @ThummeTo 

Tested this Functionality with release Version 0.1.4, the issue is resolved. I have test giving the custom `unpackpath` and it worked fine.

Closing the Issue.

Regards
Prem
