### ISSUE TITLE
Optional xml elements in modelDescription.xml not handled

### ISSUE THREAD

**Issue by AnHeuermann** [ThummeTo/FMI.jl#39]
According to `2.2.1 Definition of an FMU (fmiModelDescription)` of the [2.0.2 FMI standard](https://github.com/modelica/fmi-standard/releases/download/v2.0.2/FMI-Specification-2.0.2.pdf) a lot of xml elements are optional for the modelDescription.xml.
FMI.jl doesn't handle (all) optional elements if they are not present.

Try simulating the [fmi-cross-check VanDerPol FMU](https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/linux64/Test-FMUs/0.0.2/VanDerPol).

```julia
julia> pathToFMU="fmi-cross-check/fmus/2.0/me/linux64/Test-FMUs/0.0.2/VanDerPol/VanDerPol.fmu"
julia> myFMU = fmiLoad(pathToFMU)
ERROR: MethodError: no method matching createEnum(::Nothing)
Closest candidates are:
  createEnum(::EzXML.Node) at /home/andreas/workspace/julia/FMI.jl/src/FMI2_md.jl:253
Stacktrace:
 [1] fmi2readModelDescription(pathToModellDescription::String)
   @ FMI ~/workspace/julia/FMI.jl/src/FMI2_md.jl:59
 [2] fmi2Load(pathTofmu2::String)
   @ FMI ~/workspace/julia/FMI.jl/src/FMI2.jl:279
 [3] fmiLoad(pathToFMU::String)
   @ FMI ~/workspace/julia/FMI.jl/src/FMI.jl:85
 [4] top-level scope
   @ REPL[9]:1
```

In this case the model description is not defining `TypeDefinitions`.

**Comment by ThummeTo** [comment]
Dear @AnHeuermann, we can't reproduce the issue on Windows using the current library release (0.1.6). There is only a warning, but no error. Are you using the current version? Thanks.

**Comment by AnHeuermann** [comment]
I beliefe I was using the master branch, but apparently 805fd29046a70acd4f2a1e6cd10b41ac4f487419 does already fix this issue. So I guess I used an outdated version.
