### ISSUE TITLE
Participate in FMI Cross Check

### ISSUE THREAD

**Issue by AnHeuermann** [ThummeTo/FMI.jl#40]
Testing FMI.jl with a broad set of FMUs will improve the quality of this package.

One source of a lot of different FMUs is the FMI Cross Check: [modelica/fmi-cross-check](https://github.com/modelica/fmi-cross-check).
Testing the cross check only needs a bit of scripting and after that new bugs can be identified and solved. And after that you can of course be listed in https://fmi-standard.org/tools/ as well.

**Comment by AnHeuermann** [comment]
I can copy what I did for JuliaFMI.jl and update it to work with FMI.jl. Compare to https://github.com/AnHeuermann/JuliaFMI/blob/master/test/fmi-cross-check-tests.jl.
Maybe changing the coding style a bit would be a good idea, though.

**Comment by ThummeTo** [comment]
Thanks for the suggestion Andreas.
@JoKircher is already on this ;-)
(he's on vacation until wednesday, but my last status is that there's not too much left to do)

This is a very important point for us, too.

**Comment by ThummeTo** [comment]
[@christofbaumgartner](https://github.com/christofbaumgartner) is on this :)

**Comment by ThummeTo** [comment]
closed by #179 and #181
