### ISSUE TITLE
Any way to get access to default parameter values specified in the xml?

### ISSUE THREAD

**Issue by sharanry** [ThummeTo/FMI.jl#43]
I was looking to get access to the default parameter values specified in the modelDescription.xml. For example, I hope to get access to the `0` in the model description excerpt below through FMI. Is there currently any way to do this? If not, I am open to submitting a PR.

```xml
<ScalarVariable
    name="p_integer"
    valueReference="3"
    variability="fixed"
    causality="parameter"
    >
    <Integer start="0"/>
 </ScalarVariable>
```
@ThummeTo  
CC:  @ChrisRackauckas

**Comment by ThummeTo** [comment]
In #31d86ba the new commands `fmiGetStartValue` and `fmi2GetStartValue` are introduced, you can use them like:

`fmiGetStartValue(myFMU, "p_integer")`

**Comment by sharanry** [comment]
Thank you so much!
