### ISSUE TITLE
Add ability to pass kwargs to `solve` from `fmiSimulate` 

### ISSUE THREAD

**Issue by sharanry** [ThummeTo/FMI.jl#54]
For example, we can pass kwargs like `maxiters` or `dt`  to the ODE solvers. Currently, there is no obvious way to do this.

```julia
FMI.fmiSimulate(fmu, 0.0, 100.0; maxiters=1e7, dt=0.1, solver=OrdinaryDiffEq.Euler())
```

**Comment by ThummeTo** [comment]
Dear @sharanry ,
makes sense! We will add this in the next release!
Best regards!

**Comment by sharanry** [comment]
I actually had this implemented locally. Opened a PR>

**Comment by ThummeTo** [comment]
Thank you! 
PR is merged.
