### ISSUE TITLE
Improve DocStrings

### ISSUE THREAD

**Issue by ThummeTo** [ThummeTo/FMI.jl#67]
- [x] Improve DocString Format (linebrakes)
- [x] Start DocStrings for every function with function explanations
- [x] add automated code coverage service for repo

**Comment by ThummeTo** [comment]
> I can update the doc-strings for those and add a PR for it.

I would be very happy about that!

**Comment by ThummeTo** [comment]
Documentation based on will be deployed: https://docs.julialang.org/en/v1/manual/documentation/

**Comment by ThummeTo** [comment]
@adribrune

**Comment by adribrune** [comment]
int main() {
      printf("Hello World!\n");
      retrun 0;
}

**Comment by ThummeTo** [comment]
Closed with release 0.10.0
